package com.kastrakomnen.hmessenger.model;

public enum IndexFormation {
    INDEX_NX2_NY2,
    INDEX_NX1_NY2,
    INDEX_PX0_NY2,
    INDEX_PX1_NY2,
    INDEX_PX2_NY2,
    INDEX_NX2_NY1,
    INDEX_NX1_NY1,
    INDEX_PX0_NY1,
    INDEX_PX1_NY1,
    INDEX_PX2_NY1,
    INDEX_NX2_PY0,
    INDEX_NX1_PY0,
    INDEX_PX0_PY0,
    INDEX_PX1_PY0,
    INDEX_PX2_PY0,
    INDEX_NX2_PY1,
    INDEX_NX1_PY1,
    INDEX_PX0_PY1,
    INDEX_PX1_PY1,
    INDEX_PX2_PY1,
    INDEX_NX2_PY2,
    INDEX_NX1_PY2,
    INDEX_PX0_PY2,
    INDEX_PX1_PY2,
    INDEX_PX2_PY2
}
